### ISSUE TITLE
How to install this package with Gradle

### ISSUE THREAD

**Issue by dainius-s** [tianyirenjian/jvalidation#5]
Hi,

I love your port of validation from Laravel as I was a huge fan of many things that Laravel did very well, one of them was validation.

I am starting a project with Spring Boot + Kotlin + Gradle. How do I go about to install this with Gradle?

**Comment by tianyirenjian** [comment]
Maybe you can add `implementation group: 'com.tianyisoft.jvalidate', name: 'jvalidation', version: '1.6.0'` or `implementation("com.tianyisoft.jvalidate:jvalidation:1.6.0")`  to your build.gradle or build.gradle.kts.

I never used gradle., but I use this library with spring boot + kotlin ,  it works well.

BTW, this library only works with spring boot 2.x.

**Comment by dainius-s** [comment]
Hi,

thank you for a speedy reply. 

I am using Spring Boot 3.x so that is a bummer :(

Would you be able to recommend any similar library like yours at all?

**Comment by dainius-s** [comment]
Hi, 

I was looking at Readme and could not find anywhere mentioned that this Library only works with Spring Boot 2.x. 
It would be great if you could update the Readme just to give a heads up ;)

Thank you.
