### ISSUE TITLE
java.lang.ClassNotFoundException: javax.servlet.Filter

### ISSUE THREAD

**Issue by obadahalak** [tianyirenjian/jvalidation#6]
I get the following error when I add @EnableJValidate in Main Class, I use 1.6.1 version.
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [com.mrd.employee.Emp
loyeeApplication]: Failed to load class [javax.servlet.Filter]

**Comment by tianyirenjian** [comment]
Which version of spring boot are you using? This library is only available for spring boot 2.x.

**Comment by tianyirenjian** [comment]
If you are using spring boot 2.x version, you may refer to this link to see if you are using tomcat.

[https://stackoverflow.com/questions/30374316/spring-boot-java-lang-noclassdeffounderror-javax-servlet-filter](https://stackoverflow.com/questions/30374316/spring-boot-java-lang-noclassdeffounderror-javax-servlet-filter)
